# Generated by Django 3.0.4 on 2020-05-05 07:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='challenge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('deadline', models.DateField(default=datetime.datetime.now)),
                ('tags', models.CharField(max_length=100)),
            ],
        ),
    ]
